// =========================================================
// pgp_verify.rs — EasyWAF
// Checking a detached OpenPGP signature.
//
// Used before applying a rule set update. A rule set decides
// what traffic is refused, so one fetched over a network has
// to be provably the one that was published — HTTPS says the
// server is who it claims, not that what it served is what
// the maintainer signed.
//
// Verified in-process rather than by running gpg. Shelling
// out to a binary that may not be installed is how reading a
// certificate came to fail silently on a container built
// with --no-install-recommends.
// =========================================================

use pgp::composed::{Deserializable, DetachedSignature, SignedPublicKey};

/// Verify `data` against an armoured detached signature and an armoured key.
///
/// Returns the user id that signed it, for the log — an operator should be
/// able to see *which* key was accepted, not just that one was.
pub fn verify_detached(
    public_key_armored: &str,
    data: &[u8],
    signature_armored: &str,
) -> Result<String, String> {
    let (key, _) = SignedPublicKey::from_string(public_key_armored)
        .map_err(|e| format!("the trusted key could not be read: {e}"))?;

    let (sig, _) = DetachedSignature::from_string(signature_armored)
        .map_err(|e| format!("the signature could not be read: {e}"))?;

    let who = key
        .details
        .users
        .first()
        .map(|u| String::from_utf8_lossy(u.id.id()).to_string())
        .unwrap_or_else(|| "an unnamed key".to_string());

    // The primary key is often certification-only, with signing delegated to a
    // subkey — which is what gpg does by default. Trying only the primary would
    // reject signatures from an ordinary, correctly-formed key.
    if sig.verify(&key, data).is_ok() {
        return Ok(who);
    }
    for sub in &key.public_subkeys {
        if sig.verify(&sub.key, data).is_ok() {
            return Ok(who);
        }
    }

    Err("the signature does not match this key".to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    // Fixtures are produced by gpg in tests/fixtures/, because gpg is what
    // actually signs the channel. A key generated by this same library would
    // prove only that it agrees with itself.
    fn fixture(name: &str) -> Option<String> {
        std::fs::read_to_string(format!("tests/fixtures/{name}")).ok()
    }

    #[test]
    fn accepts_a_signature_gpg_produced() {
        let (Some(key), Some(sig), Ok(data)) = (
            fixture("pgp_key.asc"),
            fixture("pgp_good.asc"),
            std::fs::read("tests/fixtures/pgp_data.txt"),
        ) else {
            eprintln!("fixtures absent — run tests/fixtures/make.sh");
            return;
        };
        let who = verify_detached(&key, &data, &sig).expect("a good signature verifies");
        assert!(who.contains("EasyWAF"), "reports who signed: {who}");
    }

    #[test]
    fn rejects_data_that_was_altered() {
        let (Some(key), Some(sig)) = (fixture("pgp_key.asc"), fixture("pgp_good.asc")) else {
            return;
        };
        let mut data = std::fs::read("tests/fixtures/pgp_data.txt").unwrap();
        data.push(b'!');
        assert!(verify_detached(&key, &data, &sig).is_err(), "altered data must not verify");
    }

    #[test]
    fn rejects_a_signature_from_another_key() {
        let (Some(key), Some(other_sig), Ok(data)) = (
            fixture("pgp_key.asc"),
            fixture("pgp_other.asc"),
            std::fs::read("tests/fixtures/pgp_data.txt"),
        ) else {
            return;
        };
        // The signature is valid — just not by the key we trust, which is the
        // whole point of pinning one.
        assert!(verify_detached(&key, &data, &other_sig).is_err());
    }

    #[test]
    fn nonsense_is_an_error_rather_than_a_panic() {
        assert!(verify_detached("not a key", b"x", "not a signature").is_err());
        assert!(verify_detached("", b"", "").is_err());
    }
}
